version: "3.9"
services:
  superset:
    build: .
    container_name: superset
    user: "root"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
     - 8088:8088
    volumes:
     - "./superset_config.py:/app/pythonpath/superset_config.py"
     - "./data:/app/data"
    networks:
      - shared

networks:
  shared:
